### ISSUE TITLE
As a volunteer, I want to be able to create an account on the platform so that I can more easily connect with non-profit organizations, personalize my experience, and track my contributions.

### ISSUE THREAD

**Issue by lucianli** [BrianTaylor9/CS130_Project#5]
## User Story
As a volunteer, I want to be able to create an account on the platform so that I can more easily connect with non-profit organizations, personalize my experience, and track my contributions.

## Detailed Description
Volunteers should be able to sign up/login to the platform using a username and password. While signed in, they should access to a profile page that includes settings to personalize their experience and track their contribution and event history.

## Acceptance Criteria
- [x] Given a volunteer doesn't have an account, then they should be able to register through a menu link.
- [x] Given a volunteer has an account, then they should be able to log in through a menu link.
- [x] Given a volunteer is logged in, then they should be able to add organizations to a personal list.
- [x] Given a volunteer is logged in, then they should be able to view their contribution and event history.
